obj-$(CONFIG_AW_AXP) += axp-core.o
obj-$(CONFIG_AW_AXP) += axp-sysfs.o
obj-$(CONFIG_AW_AXP) += axp-virtual.o
obj-$(CONFIG_AW_AXP) += axp-powerkey.o
obj-$(CONFIG_AW_AXP) += axp-charger.o
obj-$(CONFIG_AW_AXP) += axp-gpio.o
obj-$(CONFIG_AW_AXP) += axp-regulator.o
obj-$(CONFIG_AW_AXP) += nmi/sunxi-nmi.o

#AXP2585
obj-$(CONFIG_AW_AXP2585) += axp2585/axp2585.o
obj-$(CONFIG_AW_AXP2585) += axp2585/axp2585-charger.o
obj-$(CONFIG_AW_AXP2585) += axp2585/axp2585-powerkey.o


